__author__ = 'mojdehtarighat'

"""If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.

The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

sum=0
for x in range(1,1000):
    if x%3==0 or x%5==0:
        sum=sum+x

print sum"""

"""Each new term in the Fibonacci sequence is generated by adding the previous two terms.

By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

element_before=2
element_before_before=1
new_element=0
sum=2

while new_element <=4000000:
    new_element=element_before + element_before_before
    element_before_before= element_before
    element_before= new_element
    if new_element%2==0:
        sum=sum+new_element

print sum"""

"""The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

def largest_prime_factor(n):
    i = 2
    while i * i < n:
        while n % i == 0:
            n = n / i
        i = i + 1
    return n

print largest_prime_factor(600851475143)"""