__author__ = 'mojdehtarighat'

"""Each new term in the Fibonacci sequence is generated by adding the previous two terms.

By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

element_before=2
element_before_before=1
new_element=0
sum=2

while new_element <=4000000:
    new_element=element_before + element_before_before
    element_before_before= element_before
    element_before= new_element
    if new_element%2==0:
        sum=sum+new_element

print sum